// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZlibZ4KwBqT8lwIzcplu2rE9lt5jJrHE',
    appId: '1:955852617059:web:5ad92f43a7e1911fb24f56',
    messagingSenderId: '955852617059',
    projectId: 'osc-system',
    authDomain: 'osc-system.firebaseapp.com',
    storageBucket: 'osc-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhCjPO4ySI1HIbAq5k31XZf8wR4rh38ic',
    appId: '1:955852617059:android:9525aff1ff57d9e7b24f56',
    messagingSenderId: '955852617059',
    projectId: 'osc-system',
    storageBucket: 'osc-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ4qGAXmsgVaPkk-c8_tGDKGSJIbNc_bs',
    appId: '1:955852617059:ios:ce92e433f5a5d13eb24f56',
    messagingSenderId: '955852617059',
    projectId: 'osc-system',
    storageBucket: 'osc-system.firebasestorage.app',
    iosBundleId: 'com.example.oscSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ4qGAXmsgVaPkk-c8_tGDKGSJIbNc_bs',
    appId: '1:955852617059:ios:ce92e433f5a5d13eb24f56',
    messagingSenderId: '955852617059',
    projectId: 'osc-system',
    storageBucket: 'osc-system.firebasestorage.app',
    iosBundleId: 'com.example.oscSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZlibZ4KwBqT8lwIzcplu2rE9lt5jJrHE',
    appId: '1:955852617059:web:d585317d7ae78c33b24f56',
    messagingSenderId: '955852617059',
    projectId: 'osc-system',
    authDomain: 'osc-system.firebaseapp.com',
    storageBucket: 'osc-system.firebasestorage.app',
  );
}
